<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\RecruitAI.Domain\RecruitAI.Domain.csproj" />
	</ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources\Messages.en.Designer.cs">
			<DesignTime>true</DesignTime>
			<AutoGen>true</AutoGen>
			<DependentUpon>Messages.en.resx</DependentUpon>
		</Compile>

		<Compile Update="Resources\Messages.vi.Designer.cs">
			<DesignTime>true</DesignTime>
			<AutoGen>true</AutoGen>
			<DependentUpon>Messages.vi.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>

		<PackageReference Include="Google.GenAI" Version="1.6.1" />

		<PackageReference Include="MediatR" Version="12.4.1" />

        <PackageReference Include="AutoMapper" Version="14.0.0" />

		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />

		<PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />

		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.3" />

		<PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.3" />

		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />

		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.16.0" />

		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />

	</ItemGroup>

</Project>