// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitAI.Infrastructure.Data;

#nullable disable

namespace RecruitAI.Infrastructure.Migrations
{
    [DbContext(typeof(RecruitDevContext))]
    partial class RecruitDevContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecruitAI.Domain.Entities.AuthProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<string>("ProviderEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_AuthProviders_Provider_ProviderUserId");

                    b.ToTable("AuthProviders");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.CV", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AnalyzedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("CVs");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.CVAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CVId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Confidence")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CVId");

                    b.HasIndex("SkillId");

                    b.ToTable("CVAnalysisResult");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Applications")
                        .HasColumnType("int");

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("EmploymentType")
                        .HasColumnType("int");

                    b.Property<int?>("ExperienceLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("RecruiterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Jobs_CreatedAt");

                    b.HasIndex("EmploymentType")
                        .HasDatabaseName("IX_Jobs_EmploymentType");

                    b.HasIndex("ExperienceLevel")
                        .HasDatabaseName("IX_Jobs_ExperienceLevel");

                    b.HasIndex("ExpirationDate")
                        .HasDatabaseName("IX_Jobs_ExpirationDate");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Jobs_IsDeleted");

                    b.HasIndex("Location")
                        .HasDatabaseName("IX_Jobs_Location");

                    b.HasIndex("RecruiterId")
                        .HasDatabaseName("IX_Jobs_RecruiterId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Jobs_Status");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Jobs_Title");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.JobSkill", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.HasKey("JobId", "SkillId");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("IX_JobSkills_SkillId");

                    b.ToTable("JobSkills");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("IX_PasswordResetTokens_ExpiryDate");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_PasswordResetTokens_Token");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetToken");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TokenType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpireAt")
                        .HasDatabaseName("IX_RefreshTokens_ExpireAt");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aliases")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContextKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Skills_Category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Skills_IsActive");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Skills_Name");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aliases = "CSharp,C Sharp",
                            Category = "Programming Language",
                            ContextKeywords = "c#,csharp,c sharp",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Programming Language",
                            ContextKeywords = "java,java 8,java 11",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 3,
                            Aliases = "py",
                            Category = "Programming Language",
                            ContextKeywords = "python,py,django",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 4,
                            Aliases = "js,java script,javascript",
                            Category = "Programming Language",
                            ContextKeywords = "javascript,js,ecmascript",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 5,
                            Aliases = "ts,type script,typescript",
                            Category = "Programming Language",
                            ContextKeywords = "typescript,ts",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 6,
                            Aliases = "structured query language",
                            Category = "Programming Language",
                            ContextKeywords = "sql,tsql,plsql",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 7,
                            Aliases = "golang",
                            Category = "Programming Language",
                            ContextKeywords = "go,golang",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Go"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Programming Language",
                            ContextKeywords = "rust",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Rust"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Programming Language",
                            ContextKeywords = "php,laravel",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Programming Language",
                            ContextKeywords = "swift,ios",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Swift"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Programming Language",
                            ContextKeywords = "kotlin,android",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Programming Language",
                            ContextKeywords = "ruby,rails",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = 13,
                            Aliases = "dotnet core",
                            Category = "Framework",
                            ContextKeywords = ".net core,asp.net core",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = ".NET Core"
                        },
                        new
                        {
                            Id = 14,
                            Aliases = "asp.net core,aspnetcore",
                            Category = "Framework",
                            ContextKeywords = "asp.net core,aspnet core web api",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 15,
                            Aliases = "ef,ef core",
                            Category = "Framework",
                            ContextKeywords = "entity framework,ef core",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Entity Framework"
                        },
                        new
                        {
                            Id = 16,
                            Aliases = "webapi,rest api",
                            Category = "Framework",
                            ContextKeywords = "web api,restful api",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Web API"
                        },
                        new
                        {
                            Id = 17,
                            Aliases = "restful api",
                            Category = "Framework",
                            ContextKeywords = "rest api,restful web service",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "REST API"
                        },
                        new
                        {
                            Id = 18,
                            Aliases = "reactjs",
                            Category = "Framework",
                            ContextKeywords = "react,reactjs,react.js",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "React"
                        },
                        new
                        {
                            Id = 19,
                            Aliases = "angularjs",
                            Category = "Framework",
                            ContextKeywords = "angular,angular 2+",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 20,
                            Aliases = "vue",
                            Category = "Framework",
                            ContextKeywords = "vue,vuejs",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Vue.js"
                        },
                        new
                        {
                            Id = 21,
                            Aliases = "spring",
                            Category = "Framework",
                            ContextKeywords = "spring,spring boot",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Spring Boot"
                        },
                        new
                        {
                            Id = 22,
                            Aliases = "node",
                            Category = "Framework",
                            ContextKeywords = "node,nodejs",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Framework",
                            ContextKeywords = "django,python web",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Django"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Framework",
                            ContextKeywords = "flask",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Flask"
                        },
                        new
                        {
                            Id = 25,
                            Aliases = "express",
                            Category = "Framework",
                            ContextKeywords = "express,expressjs",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Express.js"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Framework",
                            ContextKeywords = "hibernate,jpa",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Hibernate"
                        },
                        new
                        {
                            Id = 27,
                            Aliases = "mssql",
                            Category = "Database",
                            ContextKeywords = "sql server,mssql",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "SQL Server"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Database",
                            ContextKeywords = "mysql",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "MySQL"
                        },
                        new
                        {
                            Id = 29,
                            Aliases = "postgres",
                            Category = "Database",
                            ContextKeywords = "postgresql,postgres",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 30,
                            Aliases = "mongo",
                            Category = "Database",
                            ContextKeywords = "mongodb,mongo",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "MongoDB"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Database",
                            ContextKeywords = "redis,cache",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Redis"
                        },
                        new
                        {
                            Id = 32,
                            Aliases = "es",
                            Category = "Database",
                            ContextKeywords = "elasticsearch,es",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Elasticsearch"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Database",
                            ContextKeywords = "oracle",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Oracle"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Database",
                            ContextKeywords = "cassandra",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Cassandra"
                        },
                        new
                        {
                            Id = 35,
                            Aliases = "dynamo",
                            Category = "Database",
                            ContextKeywords = "dynamodb,aws dynamo",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "DynamoDB"
                        },
                        new
                        {
                            Id = 36,
                            Aliases = "microsoft azure",
                            Category = "Cloud",
                            ContextKeywords = "azure,azure devops",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Azure"
                        },
                        new
                        {
                            Id = 37,
                            Aliases = "amazon web services",
                            Category = "Cloud",
                            ContextKeywords = "aws,ec2,s3,lambda",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "AWS"
                        },
                        new
                        {
                            Id = 38,
                            Aliases = "gcp",
                            Category = "Cloud",
                            ContextKeywords = "gcp,google cloud",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Google Cloud"
                        },
                        new
                        {
                            Id = 39,
                            Category = "DevOps",
                            ContextKeywords = "docker,container",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 40,
                            Aliases = "k8s",
                            Category = "DevOps",
                            ContextKeywords = "kubernetes,k8s",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Kubernetes"
                        },
                        new
                        {
                            Id = 41,
                            Category = "DevOps",
                            ContextKeywords = "jenkins,ci/cd",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Jenkins"
                        },
                        new
                        {
                            Id = 42,
                            Category = "DevOps",
                            ContextKeywords = "git,github,gitlab",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Git"
                        },
                        new
                        {
                            Id = 43,
                            Category = "DevOps",
                            ContextKeywords = "terraform,iac",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Terraform"
                        },
                        new
                        {
                            Id = 44,
                            Category = "DevOps",
                            ContextKeywords = "ansible",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Ansible"
                        },
                        new
                        {
                            Id = 45,
                            Aliases = "collaboration",
                            Category = "Soft Skill",
                            ContextKeywords = "teamwork,team work",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Teamwork"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Soft Skill",
                            ContextKeywords = "communication,verbal,written",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Communication"
                        },
                        new
                        {
                            Id = 47,
                            Aliases = "analytical",
                            Category = "Soft Skill",
                            ContextKeywords = "problem solving,analytical",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Problem Solving"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Soft Skill",
                            ContextKeywords = "leadership,lead",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Leadership"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Soft Skill",
                            ContextKeywords = "time management,organize",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Time Management"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Language",
                            ContextKeywords = "english,ielts,toeic",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "English"
                        },
                        new
                        {
                            Id = 51,
                            Aliases = "tiếng việt",
                            Category = "Language",
                            ContextKeywords = "vietnamese,tieng viet",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Vietnamese"
                        },
                        new
                        {
                            Id = 52,
                            Aliases = "日本語",
                            Category = "Language",
                            ContextKeywords = "japanese,nihongo,jlpt",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = 53,
                            Aliases = "mandarin",
                            Category = "Language",
                            ContextKeywords = "chinese,mandarin",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Chinese"
                        },
                        new
                        {
                            Id = 54,
                            Aliases = "한국어",
                            Category = "Language",
                            ContextKeywords = "korean,topik",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Korean"
                        },
                        new
                        {
                            Id = 55,
                            Aliases = "json web token",
                            Category = "Security",
                            ContextKeywords = "jwt authentication,jwt token",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "JWT"
                        },
                        new
                        {
                            Id = 56,
                            Aliases = "oauth 2.0",
                            Category = "Security",
                            ContextKeywords = "oauth2,oauth 2.0",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "OAuth2"
                        },
                        new
                        {
                            Id = 57,
                            Aliases = "microservice",
                            Category = "Architecture",
                            ContextKeywords = "microservices architecture,msa",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Microservices"
                        },
                        new
                        {
                            Id = 58,
                            Aliases = "onion architecture",
                            Category = "Architecture",
                            ContextKeywords = "clean architecture,onion architecture",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Clean Architecture"
                        },
                        new
                        {
                            Id = 59,
                            Aliases = "cqrs pattern",
                            Category = "Architecture",
                            ContextKeywords = "cqrs,command query responsibility segregation",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "CQRS"
                        },
                        new
                        {
                            Id = 60,
                            Aliases = "event sourcing pattern",
                            Category = "Architecture",
                            ContextKeywords = "event sourcing,event driven",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Event Sourcing"
                        },
                        new
                        {
                            Id = 61,
                            Aliases = "unit test",
                            Category = "Testing",
                            ContextKeywords = "unit testing,xunit,nunit",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Unit Testing"
                        },
                        new
                        {
                            Id = 62,
                            Aliases = "integration test",
                            Category = "Testing",
                            ContextKeywords = "integration testing",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Integration Testing"
                        },
                        new
                        {
                            Id = 63,
                            Aliases = "xunit.net",
                            Category = "Testing",
                            ContextKeywords = "xunit,unit testing",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "xUnit"
                        },
                        new
                        {
                            Id = 64,
                            Aliases = "mock",
                            Category = "Testing",
                            ContextKeywords = "moq,mocking",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Moq"
                        },
                        new
                        {
                            Id = 65,
                            Aliases = "html",
                            Category = "Frontend",
                            ContextKeywords = "html5,html",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "HTML5"
                        },
                        new
                        {
                            Id = 66,
                            Aliases = "css",
                            Category = "Frontend",
                            ContextKeywords = "css3,css",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "CSS3"
                        },
                        new
                        {
                            Id = 67,
                            Category = "Frontend",
                            ContextKeywords = "bootstrap,css framework",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Bootstrap"
                        },
                        new
                        {
                            Id = 68,
                            Aliases = "tailwind",
                            Category = "Frontend",
                            ContextKeywords = "tailwind,tailwindcss",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Tailwind CSS"
                        },
                        new
                        {
                            Id = 69,
                            Aliases = "jquery",
                            Category = "Frontend",
                            ContextKeywords = "jquery,javascript library",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "jQuery"
                        },
                        new
                        {
                            Id = 70,
                            Aliases = "html5",
                            Category = "Frontend",
                            ContextKeywords = "html,html5",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "HTML"
                        },
                        new
                        {
                            Id = 71,
                            Aliases = "css3",
                            Category = "Frontend",
                            ContextKeywords = "css,css3",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "CSS"
                        },
                        new
                        {
                            Id = 72,
                            Aliases = "tailwind css",
                            Category = "Frontend",
                            ContextKeywords = "tailwind,tailwindcss",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Tailwind"
                        },
                        new
                        {
                            Id = 73,
                            Aliases = "reduxjs",
                            Category = "Frontend",
                            ContextKeywords = "redux,reduxjs,react redux",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Redux"
                        },
                        new
                        {
                            Id = 74,
                            Aliases = "reactnative",
                            Category = "Mobile",
                            ContextKeywords = "react native,mobile app",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "React Native"
                        },
                        new
                        {
                            Id = 75,
                            Category = "Mobile",
                            ContextKeywords = "flutter,dart",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Flutter"
                        },
                        new
                        {
                            Id = 76,
                            Aliases = "android dev",
                            Category = "Mobile",
                            ContextKeywords = "android,kotlin android",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Android"
                        },
                        new
                        {
                            Id = 77,
                            Aliases = "iphone",
                            Category = "Mobile",
                            ContextKeywords = "ios,swift ios",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "iOS"
                        },
                        new
                        {
                            Id = 78,
                            Aliases = "rabbit mq",
                            Category = "Message Queue",
                            ContextKeywords = "rabbitmq,message queue",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "RabbitMQ"
                        },
                        new
                        {
                            Id = 79,
                            Aliases = "apache kafka",
                            Category = "Message Queue",
                            ContextKeywords = "kafka,event streaming",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Kafka"
                        },
                        new
                        {
                            Id = 80,
                            Aliases = "service bus",
                            Category = "Message Queue",
                            ContextKeywords = "azure service bus,servicebus",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Azure Service Bus"
                        },
                        new
                        {
                            Id = 81,
                            Aliases = "redis pubsub",
                            Category = "Message Queue",
                            ContextKeywords = "redis pubsub,redis messaging",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            Name = "Redis Pub/Sub"
                        });
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Tests__3214EC071C177EA5");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PermissionCodes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.AuthProvider", b =>
                {
                    b.HasOne("RecruitAI.Domain.Entities.User", "User")
                        .WithMany("AuthProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.CV", b =>
                {
                    b.HasOne("RecruitAI.Domain.Entities.User", "User")
                        .WithMany("CVs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.CVAnalysisResult", b =>
                {
                    b.HasOne("RecruitAI.Domain.Entities.CV", "CV")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("CVId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitAI.Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CV");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.Job", b =>
                {
                    b.HasOne("RecruitAI.Domain.Entities.User", "Recruiter")
                        .WithMany()
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.JobSkill", b =>
                {
                    b.HasOne("RecruitAI.Domain.Entities.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitAI.Domain.Entities.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("RecruitAI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("RecruitAI.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.CV", b =>
                {
                    b.Navigation("AnalysisResults");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.Job", b =>
                {
                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.Skill", b =>
                {
                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("RecruitAI.Domain.Entities.User", b =>
                {
                    b.Navigation("AuthProviders");

                    b.Navigation("CVs");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
