using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.IdentityModel.Tokens;
using RecruitAI.Application.Helpers;  
using RecruitAI.Application.Interfaces.Services;
using RecruitAI.Domain.Entities;
using RecruitAI.Domain.Enums;
using RecruitAI.Domain.Exceptions;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

namespace RecruitAI.Application.Services
{
	public class JwtService : IJwtService
	{
		private readonly IConfiguration _configuration;
		private readonly ILogger<JwtService> _logger;
		private readonly IMessageService _msg;
		private readonly string _key;

		public JwtService(
			IConfiguration configuration,
			ILogger<JwtService> logger,
			IMessageService messageService)
		{
			_configuration = configuration;
			_logger = logger;
			_msg = messageService;

			// Ưu tiên 1: Environment Variable
			_key = Environment.GetEnvironmentVariable("Jwt__Key");

			// Ưu tiên 2: appsettings.json
			if (string.IsNullOrEmpty(_key))
				_key = _configuration["Jwt:Key"];

			// Ưu tiên 3: Auto-generate cho development
			if (string.IsNullOrEmpty(_key))
			{
				_key = GenerateRandomKey(32);
				_logger.LogWarning(_msg.Log("JwtKeyAutoGenerated"), _key);
			}
		}

		private string GenerateRandomKey(int length)
		{
			const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
			var random = new Random();
			return new string(Enumerable.Repeat(chars, length)
				.Select(s => s[random.Next(s.Length)]).ToArray());
		}

		public Task<string> GenerateToken(User user)
		{
			try
			{
				if (user == null)
					_msg.Throw(ErrorCode.ValidationFailed, "UserNull"); 

				if (user.Id == Guid.Empty)
					_msg.Throw(ErrorCode.ValidationFailed, "UserIdEmpty"); 

				if (string.IsNullOrEmpty(user.Email))
					_msg.Throw(ErrorCode.ValidationFailed, "UserEmailEmpty"); 

				var claims = new[]
				{
					new Claim(JwtRegisteredClaimNames.Sub, user.Id.ToString()),
					new Claim(JwtRegisteredClaimNames.Email, user.Email),
					new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString())
				};

				// Dùng _key đã được khởi tạo ở constructor
				if (string.IsNullOrEmpty(_key))
					_msg.Throw(ErrorCode.InternalServerError, "JwtKeyNotConfigured"); 

				var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_key));
				var creds = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);

				// Đọc thời gian hết hạn từ config
				var expiryMinutes = _configuration.GetValue<int>("Jwt:ExpiryMinutes", 15);

				var token = new JwtSecurityToken(
					issuer: _configuration["Jwt:Issuer"],
					audience: _configuration["Jwt:Audience"],
					claims: claims,
					expires: DateTime.UtcNow.AddMinutes(expiryMinutes),
					signingCredentials: creds
				);

				return Task.FromResult(new JwtSecurityTokenHandler().WriteToken(token));
			}
			catch (BusinessException)
			{
				throw;
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, _msg.Log("JwtGenerationError"), user?.Id);
				_msg.Throw(ErrorCode.InternalServerError, "JwtGenerationFailed", ex, ex.Message); 
				return null; // Never reached
			}
		}
	}
}