using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.IdentityModel.Tokens;
using RecruitAI.Shared.Helpers;
using RecruitAI.Shared.Interfaces;
using RecruitAI.Domain.Entities;
using RecruitAI.Domain.Enums;
using RecruitAI.Domain.Exceptions;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using RecruitAI.Shared.Interfaces;

namespace RecruitAI.Infrastructure.Services
{
	public class JwtService : IJwtService
	{
		private readonly IConfiguration _configuration;
		private readonly ILogger<JwtService> _logger;
		private readonly IMessageService _msg;
		private readonly string _key;

		public JwtService(
			IConfiguration configuration,
			ILogger<JwtService> logger,
			IMessageService messageService)
		{
			_configuration = configuration;
			_logger = logger;
			_msg = messageService;

			// Ưu tiên 1: Environment Variable
			_key = Environment.GetEnvironmentVariable("Jwt__Key");

			// Ưu tiên 2: appsettings.json
			if (string.IsNullOrEmpty(_key))
				_key = _configuration["Jwt:Key"];

			// Ưu tiên 3: Auto-generate cho development
			if (string.IsNullOrEmpty(_key))
			{
				_key = GenerateRandomKey(32);
				_logger.LogWarning(_msg.Log("JwtKeyAutoGenerated"), _key);
			}
		}

		private string GenerateRandomKey(int length)
		{
			const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
			var random = new Random();
			return new string(Enumerable.Repeat(chars, length)
				.Select(s => s[random.Next(s.Length)]).ToArray());
		}

		public Task<string> GenerateToken(User user, CancellationToken cancellationToken = default)
		{
			try
			{
				// Kiểm tra cancellation
				if (cancellationToken.IsCancellationRequested)
				{
					_logger.LogWarning("Token generation cancelled");
					cancellationToken.ThrowIfCancellationRequested();
				}

				if (user == null)
					_msg.Throw(ErrorCode.ValidationFailed, "UserNull");

				if (user.Id == Guid.Empty)
					_msg.Throw(ErrorCode.ValidationFailed, "UserIdEmpty");

				if (string.IsNullOrEmpty(user.Email))
					_msg.Throw(ErrorCode.ValidationFailed, "UserEmailEmpty");

				var claims = new List<Claim>
		{
				new Claim(JwtRegisteredClaimNames.Sub, user.Id.ToString()),
				new Claim(JwtRegisteredClaimNames.Email, user.Email),
				new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),
				new Claim(ClaimTypes.Name, user.FullName),
				new Claim(ClaimTypes.Role, user.Role.ToString()),
				new Claim("role", user.Role.ToString())
		};

				// Thêm permissions vào claims
				var permissions = user.GetPermissionList();
				if (permissions != null && permissions.Any())
				{
					foreach (var permission in permissions)
					{
						if (!string.IsNullOrWhiteSpace(permission))
						{
							claims.Add(new Claim("permission", permission.Trim()));
						}
					}
					_logger.LogInformation("Added {Count} permission claims for user {UserId}",
						permissions.Count, user.Id);
				}


				// Kiểm tra cancellation trước khi tạo token
				if (cancellationToken.IsCancellationRequested)
				{
					_logger.LogWarning("Token generation cancelled before signing");
					cancellationToken.ThrowIfCancellationRequested();
				}

				// Dùng _key đã được khởi tạo ở constructor
				if (string.IsNullOrEmpty(_key))
					_msg.Throw(ErrorCode.InternalServerError, "JwtKeyNotConfigured");

				var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_key));
				var creds = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);

				// Đọc thời gian hết hạn từ config
				var expiryMinutes = _configuration.GetValue<int>("Jwt:ExpiryMinutes", 15);

				var token = new JwtSecurityToken(
					issuer: _configuration["Jwt:Issuer"],
					audience: _configuration["Jwt:Audience"],
					claims: claims,
					expires: DateTime.UtcNow.AddMinutes(expiryMinutes),
					signingCredentials: creds
				);

				// Log thành công (không cần database)
				_logger.LogDebug("Token generated successfully for user {UserId}", user.Id);

				return Task.FromResult(new JwtSecurityTokenHandler().WriteToken(token));
			}
			catch (OperationCanceledException)
			{
				_logger.LogWarning("Token generation was cancelled");
				throw;
			}
			catch (BusinessException)
			{
				throw;
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, _msg.Log("JwtGenerationError"), user?.Id);
				_msg.Throw(ErrorCode.InternalServerError, "JwtGenerationFailed", ex, ex.Message);
				return null; // Never reached
			}
		}

		/// <summary>
		/// Phương thức xác thực token (nếu cần)
		/// </summary>
		public Task<bool> ValidateTokenAsync(string token, CancellationToken cancellationToken = default)
		{
			try
			{
				if (cancellationToken.IsCancellationRequested)
					cancellationToken.ThrowIfCancellationRequested();

				if (string.IsNullOrEmpty(token))
					return Task.FromResult(false);

				var tokenHandler = new JwtSecurityTokenHandler();
				var key = Encoding.UTF8.GetBytes(_key);

				var validationParameters = new TokenValidationParameters
				{
					ValidateIssuerSigningKey = true,
					IssuerSigningKey = new SymmetricSecurityKey(key),
					ValidateIssuer = true,
					ValidIssuer = _configuration["Jwt:Issuer"],
					ValidateAudience = true,
					ValidAudience = _configuration["Jwt:Audience"],
					ValidateLifetime = true,
					ClockSkew = TimeSpan.Zero
				};

				tokenHandler.ValidateToken(token, validationParameters, out _);

				return Task.FromResult(true);
			}
			catch (OperationCanceledException)
			{
				_logger.LogWarning("Token validation cancelled");
				throw;
			}
			catch (Exception ex)
			{
				_logger.LogDebug(ex, "Token validation failed");
				return Task.FromResult(false);
			}
		}
	}
}